Inventory and items
FailedIndustry/Industrial-Failure pull request #24
Opened 2023-12-10 07:10 UTC by PhiYerion

The current implementation is stable and includes an inventory system that we are likely to use. Not finished, but mostly to keep main as up to date as possible.

2023-12-11 07:20 UTC, PhiYerion reviewed
Changes need to be made.

2023-12-11 07:20 UTC, PhiYerion commented on GenericResult.gd
> +class GenericResult:
Where is this even used

2023-12-11 07:20 UTC, PhiYerion commented on Main.gd
> +	datetime = datetime.replace(":", "-")
This should already be in main

2023-12-11 07:20 UTC, PhiYerion commented on dev.md
Not related

2023-12-11 07:20 UTC, PhiYerion commented on entities/item/item-data.gd
> +@export var quantity: int = 1
No error handling on <= 0. There should be a setter implemented here

2023-12-11 07:20 UTC, PhiYerion commented on entities/item/item-data.gd
> +var owner: Object
Where is this ever set?

2023-12-11 07:20 UTC, PhiYerion commented on entities/items/item.tscn
> +collision_layer = 32768
This doesn't seem right. We have a layer for items.

2023-12-11 07:20 UTC, PhiYerion commented on game-explanation.md
Not related

2023-12-11 07:20 UTC, PhiYerion commented on lore.md
Empty

2023-12-11 07:20 UTC, PhiYerion commented on pitch.md
Not related

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/category.gd
> +		Logger.info("set_category: adding %s" % i)
Info is too high of a level

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/grabbed_slot.gd
> +func set_item(item: ItemData):
There should be error handling in case of <= 0

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/inventory_gui.gd
> +	Logger.info("inv: %s" % self)
Vague

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/inventory_gui.gd
> +		Logger.info("inventory.create: adding %s" % i)
Too high level

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/slot.gd
> +## There is potential for an error if [method _ready] gets called before
I think there is a check we can add for this

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/slot.gd
> +	Logger.info("setting texture to %s from %s" % [item.texture, texture_rect.texture])
Too high of a level. Probably not needed anyways

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/GUI/slot.gd
> +			Logger.info("Grabbing")
Too high of level

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/inv.tscn
> +const Slot = preload(\"res://player/inventory/inv_slot.tscn\")
Why is there \" here?

2023-12-11 07:20 UTC, PhiYerion commented on player/inventory/inv.tscn
There should not be script in here. inv_slot is no longer even a file

2023-12-11 19:26 UTC, oebelysk commented on player/inventory/inv.tscn
> +const Slot = preload(\"res://player/inventory/inv_slot.tscn\")
You tell me bro you wrote it

2023-12-11 19:28 UTC, PhiYerion commented on player/inventory/inv.tscn
> +const Slot = preload(\"res://player/inventory/inv_slot.tscn\")
Not due to the \\", but due to the file no longer existing. This would cause an error if the embedded script were run, but I think it is being bypassed as of now

2023-12-11 22:32 UTC, PhiYerion commented on dev.md
Whatever

2023-12-12 06:26 UTC, oebelysk commented on dev.md
> +We are a (relatively) small group of developers and freinds without huge money
*friends

Otherwise good paragraph and explanation of the project.

2023-12-12 06:27 UTC, oebelysk commented on dev.md
> +Although we do have a list of speicific things to create and add to the project
*specific

2023-12-12 06:28 UTC, oebelysk commented on dev.md
> +of unprefomant code will always be better than implimenting preformant
*unpreformant

2023-12-12 06:30 UTC, oebelysk commented on dev.md
> +do need some kind of inventory system. However, adding funcionality for items to
functionality*

2023-12-12 06:58 UTC, oebelysk requested changes
Suggestions for spelling improvements, rewordings, and code comments.

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +We are a (relatively) small group of developers and freinds without huge money
*friends

Otherwise good paragraph and explanation of the project.

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +debt, preconcieved opinions, deadlines, investors or shareholders breathing down
*preconceived

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +Although we do have a list of speicific things to create and add to the project
specific*

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +ideas, better versions of old ideas, or an entirely new way of implimenting some
implementing*

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +reducing time-cost. An interesting, engaging concept implimented in five lines
*implemented

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +of unprefomant code will always be better than implimenting preformant
*unperformant
*implemented

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +do need some kind of inventory system. However, adding funcionality for items to
functionality*

2023-12-12 06:58 UTC, oebelysk commented on dev.md
> +commit the work you have already done and more on to something else that
move on to*

2023-12-12 06:58 UTC, oebelysk commented on entities/item/item-wrapper.gd
> +func set_quantity(value: int) -> void:
Add a simple comment about set_quantity usage.

2023-12-12 06:58 UTC, oebelysk commented on game-explanation.md
> +will put these requirements on the player base. A default, base social
Change first sentence to

"We aim to avoid hard-coding in item vendors, factions, NPC police/military forces, and other roleplay mechanisms; instead, we hope to encourage players to organically develop and create these systems themselves."

2023-12-12 06:58 UTC, oebelysk commented on game-explanation.md
> +pseudo-Skynet will initially be put into place to make the game run smoothly at
Change "pseudo-Skynet" to

"an autonomous, apathetic artificial-intelligence overlord"

2023-12-12 06:58 UTC, oebelysk commented on pitch.md
> +dystopia where a pseudo-Skynet reigns supreme. This multiplayer RPG grants
Change "a pseudo-Skynet" to

"an autonomous, apathetic artificial-intelligence overlord"

2023-12-12 06:58 UTC, oebelysk commented on player/inventory/inventory.gd
> +func drop_type(index: int) -> int:
Would be good to leave a comment and expand on what this does.

2023-12-12 06:58 UTC, oebelysk commented on player/inventory/inventory.gd
> +func drop(index: int, amount: int) -> int:
Ditto.

2023-12-12 06:58 UTC, oebelysk commented on player/inventory/GUI/inventory_gui.gd
> +func create(inventory_owner: Player) -> void:
All of the functions in this script could have a basic comment explaining their functionality.

2023-12-12 22:00 UTC, merged